ALTER TABLE badges ADD COLUMN IF NOT EXISTS class SMALLINT;
ALTER TABLE badges ADD COLUMN IF NOT EXISTS tag_based BOOLEAN;
ALTER TABLE post_history ADD COLUMN IF NOT EXISTS content_license TEXT;
ALTER TABLE posts ADD COLUMN IF NOT EXISTS content_license TEXT;
